### PR TITLE
SPATEM & MAPEM support

### PR DESCRIPTION
**Pull request by buraksenkus**
Regarding the issue I've opened (#139),

- ASN files have been added.
   - ASN files were taken from [here](http://oldforge.etsi.org/websvn/listing.php?repname=ITS.ITS_ASN1).
   - There were some duplicates in `ISO_TS_19091_CPM.asn` and `DSRC_REG_D.asn` files so one of them had to be changed. Therefore, the `ISO_TS_19091_CPM.asn` file was removed and missing fields such as **VehicleHeight** were added into the `DSRC_REG_D.asn`.
- Generation operation has been performed and classes are created.
- Related wrapper header files have been added.

SPATEM and MAPEM messages are ready to use.

### CODE REVIEW

**Comment by riebl** [comment]
Dear @buraksenkus,

Thanks a lot for sharing your efforts! Are you sure those ASN.1 definitions reflect the latest message revision? I think https://forge.etsi.org/rep/ITS/asn1/is_ts103301 has more up-to-date versions of SPATEM and MAPEM.

**Comment by buraksenkus** [comment]
Dear @riebl,

I think you're right. I unintentionally didn't check the repository you mentioned. I'll update PR when I'm available.

**Comment by buraksenkus** [comment]
Hi @riebl,

I've updated the PR using the latest ASN.1 definitions from the repository you specified. I think there is no problem other than that. I'd be happy to help if there's anything else that needs fixing.

Note: Since the Heading, HeadingConfidence and SpeedConfidence definitions in the `ISO-TS-19091-addgrp-C-2018.asn` file on [this](https://standards.iso.org/iso/ts/19091/ed-2/en/) site conflict with the definitions in the ITS-Container module, I added **DSRC** suffix to them since it is done in this way in the given repository.

**Comment by buraksenkus** [comment]
I just noticed an **Reg_NodeOffsetPointXY_t** error during the build operation. I will try to solve it.

**Comment by buraksenkus** [comment]
Finally I've solved the problem and updated the PR. Now, ASN.1 definitions are the latest ones.

In this comment https://github.com/riebl/vanetza/pull/140#issuecomment-1033680563, I said that I updated the ASN.1 files to the latest version, but I also encountered the circular dependency problem mentioned [here](https://github.com/vlm/asn1c/issues/272). I don't know if the problem is caused by defining ASN.1 files or by asn1c, but with the help of @pitzor, I added the **-fno-include-deps** flag to asn1c command and the problem has been solved. This caused changes in many files although most of them were not functional.

Also, I had to change the cam_functions.hpp/cpp a little bit because of include statements.

I've tested the content of the MAPEMs in Wireshark and it works as expected.

image

I wouldn't want to change the existing codes too much, but I couldn't solve the situation without doing them. I hope there is nothing that I have missed.

**Comment by riebl** [comment]
Thanks for your efforts @buraksenkus! I will have a closer look as soon as possible.

**Comment by riebl** [comment]
@buraksenkus Can you please review my *mapem_spatem* branch? Does it fulfil your needs?

**Comment by buraksenkus** [comment]
It fulfils my needs. Thanks for your effort @riebl!

**Comment by riebl** [comment]
Thanks for your feedback @buraksenkus. I have merged the MAPEM and SPATEM messages into the *master* branch.

**Pull request closed without merging**
