### PR TITLE
Update to Cohda SDK R17 and upper version

### PR DESCRIPTION
**Pull request by bma67**
Just a small fix to compile with Cohda SDK R17.x

### CODE REVIEW

**Comment by riebl** [comment]
Does this break compatibility with older Cohda SDK releases?

**Comment by bma67** [comment]
Yes, it does because Cohda simply renamed a variable member from a structure.

**Comment by Sanjaer** [comment]
I encountered this problem too, there is a change in the names of several fields in mk2mac-api-types.h

**Comment by riebl** [comment]
Obsolete by now because I have removed the tools *proxy_fake_feed* and *cohda_proxy*. They have never been closely related to Vanetza after all.

**Pull request closed without merging**
